# Generated by Django 4.0.3 on 2023-04-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_status_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
